In [1]:
import numpy as np

### 1. Транспонирование матрицы (3 способа)

1. Свойство `.T` — самый частый и удобный способ.  

2. Функция `np.transpose(A)` — аналогична свойству .T.  

3. Метод `A.swapaxes(0, 1)` — меняет местами нулевую и первую оси.  


In [ ]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])

A_transposed = A.T

print(A_transposed)
# Выведет:
# [[1, 4]
#  [2, 5]
#  [3, 6]]


### 2. Умножение матриц (3 способа)

1. Оператор `@` — современный, стандартный и наиболее читаемый способ в Python 3.5+.  

2. Функция `np.dot(A, B)` — классический метод NumPy.  

3. Функция `np.matmul(A, B)` — специализированная функция для матричного умножения   (предпочтительна при работе с многомерными тензорами).

In [ ]:
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

# Матричное умножение с помощью оператора @
C = A @ B

print(C)
# Выведет:
# [[19, 22]
#  [43, 50]]


### 3. Обращение матриц

In [ ]:
A = np.array([[1, 2],
              [3, 4]])

# Вычисление обратной матрицы
A_inverse = np.linalg.inv(A)

print(A_inverse)
# Выведет:
# [[-2.   1. ]
#  [ 1.5 -0.5]]

# Проверка: A умножить на A_inverse должна получиться единичная матрица
print(np.round(A @ A_inverse))
# Выведет:
# [[1. 0.]
#  [0. 1.]]


### Массивы в numpy  

Массивы в numpy это `объекты класса ndarray` (англ. n-dimensional array)

одномерный массив — аналог списка  
двумерный массив — аналог таблицы или матрицы  
трёхмерный и выше — тензоры (ml, cv)

In [ ]:
import numpy as np

a = np.array([1, 2, 3, 4])
b = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])
print(f"a[0] = {a[0]}")
print(f"b[0] = {b[0]}")


a[0] = 1
b[0] = [1 2]


### Атрибуты ndarray

`ndarray.ndim` — количество осей массива (его размерность);  

`ndarray.shape` — кортеж с количеством элементов по каждой из осей;  

`ndarray.size` — общее число элементов в массиве;  

`ndarray.dtype` — тип данных, хранящихся в массиве;  

`ndarray.itemsize` — количество байт, которое занимает один элемент.  

In [3]:
import numpy as np

a = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])
print(f"a.ndim = {a.ndim}, a.shape = {a.shape}, a.size = {a.size}, a.dtype = {a.dtype}")


a.ndim = 2, a.shape = (4, 2), a.size = 8, a.dtype = int64


каждый тип данных имеет фиксированный диапазон допустимых значений.

In [ ]:
import numpy as np

a = np.array([1, 2, 3], dtype="uint8")
a[0] = 256
print(a)

# Попытка записать 256 приводит к переполнению: значение обнуляется
# [0 2 3] 


авто тип

In [ ]:
import numpy as np

a = np.array([1, 2.5, 3])
print(a)       # [1.  2.5 3. ]
print(a.dtype) # float64

b = np.array(['text', 1, 2.5])
print(b)       # ['text' '1' '2.5']
print(b.dtype) # <U32

# В массиве a есть вещественное число, поэтому все значения были приведены к типу float64. 
# В массиве b присутствует строка, и в результате все элементы приведены к строковому типу


Создание массивов

In [ ]:
import numpy as np

a = np.zeros((4, 3))
print(a)
print()
a = np.zeros((4, 3), dtype="int32")
print(a)

# Вывод программы

# [[0. 0. 0.]

# [0. 0. 0.]

# [0. 0. 0.]

# [0. 0. 0.]]



# [[0 0 0]

# [0 0 0]

# [0 0 0]

# [0 0 0]]


In [ ]:
import numpy as np

a = np.ones((4, 3))
print(a)

# Вывод

# [[1. 1. 1.]

# [1. 1. 1.]

# [1. 1. 1.]

# [1. 1. 1.]]


In [ ]:
import numpy as np

a = np.eye(5, 5, dtype="int8")
print(a)

# Вывод

# [[1 0 0 0 0]

# [0 1 0 0 0]

# [0 0 1 0 0]

# [0 0 0 1 0]

# [0 0 0 0 1]]


Диапазоны значений

In [ ]:
import numpy as np

a = np.arange(1, 10)
print(a)
print()
a = np.arange(1, 5, 0.4)
print(a)

# Вывод

# [1 2 3 4 5 6 7 8 9]

#

# [1.  1.4 1.8 2.2 2.6 3.  3.4 3.8 4.2 4.6]


In [ ]:
import numpy as np

# создаёт массив из заданного числа равномерно распределённых значений на отрезке
a = np.linspace(1, 5, 10)
print(a)

# Вывод

# [1. 1.44444444 1.88888889 2.33333333 2.77777778 3.22222222 3.66666667 4.11111111 4.55555556 5.]


Изменение размерности массива

In [ ]:
import numpy as np

a = np.zeros((4, 3), dtype="uint8")
print(a)
print()
a = a.reshape((2, 6))  # создаёт новый массив
print(a)

# Вывод

# [[0 0 0]

# [0 0 0]

# [0 0 0]

# [0 0 0]]

#

# [[0 0 0 0 0 0]

# [0 0 0 0 0 0]]


In [ ]:
import numpy as np

a = np.zeros((4, 3), dtype="uint8")
print(a)
print()
a.resize((2, 2, 3))  # изменяет исходный массив
print(a)

# Вывод

# [[0 0 0]

# [0 0 0]

# [0 0 0]

# [0 0 0]]

#

# [[[0 0 0]

# [0 0 0]]

#

# [[0 0 0]

# [0 0 0]]]


In [ ]:
import numpy as np

a = np.zeros((4, 3), dtype="uint8")
print(a)
print()
a = a.reshape((2, 3, -1))  # -1 автоматически вычислит нужное значение (2, 3, 2)
print(a)

# Вывод

# [[0 0 0]

# [0 0 0]

# [0 0 0]

# [0 0 0]]

#

# [[[0 0]

# [0 0]

# [0 0]]

#

# [[0 0]

# [0 0]

# [0 0]]]


Арифметика и операции над массивами  

Все стандартные арифметические операции `+, -, *, /` применяются поэлементно. Размерности массивов при этом должны совпадать

In [ ]:
import numpy as np

a = np.array([9, 8, 7])
b = np.array([1, 2, 3])
print(a + b)
print(a - b)
print(a * b)
print(a / b)

# Вывод

# [10 10 10]

# [8 6 4]

# [9 16 21]

# [9. 4. 2.33333333]


Поворот массива

In [ ]:
import numpy as np

a = np.arange(1, 13).reshape(4, 3)
print(a)
print("Поворот влево")
print(np.rot90(a))
print("Поворот вправо")
print(np.rot90(a, -1))

# [[ 1  2  3]

# [ 4  5  6]

# [ 7  8  9]

# [10 11 12]]

# Транспонирование

# [[ 1  4  7 10]

# [ 2  5  8 11]

# [ 3  6  9 12]]

# Поворот влево

# [[ 3  6  9 12]

# [ 2  5  8 11]

# [ 1  4  7 10]]

# Поворот вправо

# [[10  7  4  1]

# [11  8  5  2]

# [12  9  6  3]]



Агрегатные функции  

Функции `sum(), min(), max()` работают по умолчанию со всем массивом

In [ ]:
import numpy as np

a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
print(a.sum())
print(a.min())
print(a.max())

# Вывод
# 45
# 1
# 9



a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
print(a.sum(axis=0))  # Сумма по столбцам
print(a.sum(axis=1))  # Сумма по строкам
print(a.min(axis=0))  # Минимум по столбцам
print(a.max(axis=1))  # Максимум по строкам

# Вывод
# [12 15 18]
# [ 6 15 24]
# [1 2 3]
# [3 6 9]


Индексация, срезы и обход массива  

Массивы numpy поддерживают расширенные возможности индексирования

In [ ]:
import numpy as np

a = np.arange(1, 13).reshape(3, 4)
print(a)
print()
print(a[:2, 2:])     # Срез: 2 строки, последние 2 столбца
print()
print(a[:, ::2])     # Срез всех строк, каждый второй столбец

# Вывод

# [[ 1  2  3  4]
# [ 5  6  7  8]
# [ 9 10 11 12]]

# [[3 4]
# [7 8]]

# [[ 1  3]
# [ 5  7]
# [ 9 11]]



# По первой оси массива можно пройтись в цикле for, как по списку:
import numpy as np

a = np.arange(1, 13).reshape(3, 4)
print(a)
for row in a:
    print(row)

# Вывод

# [[ 1  2  3  4]
# [ 5  6  7  8]
# [ 9 10 11 12]]

# [1 2 3 4]
# [5 6 7 8]
# [ 9 10 11 12]


Линеаризация массива  

Обработать все элементы многомерного массива как единую последовательность.

In [ ]:
import numpy as np

a = np.arange(1, 13).reshape(3, 4)
print(a)
print()
print("; ".join(str(el) for el in a.flat))

# Вывод

# [[ 1  2  3  4]
# [ 5  6  7  8]
# [ 9 10 11 12]]

# 1; 2; 3; 4; 5; 6; 7; 8; 9; 10; 11; 12


Преимущества numpy (в 30 раз быстрее)

In [4]:
import numpy as np
from time import time

t = time()
print(f"Результат итератора: {sum(x **0.5 for x in range(10** 7))}.")
print(f"{time() - t} с.")
t = time()
print(f"Результат numpy: {np.sqrt(np.arange(10 ** 7)).sum()}.")
print(f"{time() - t} с.")

# Вывод программы

# Результат итератора: 21081849486.439312

# 1.7823209762573242 с

# Результат numpy: 21081849486.442448

# 0.05197310447692871 с


Результат итератора: 21081849486.439312.
0.697277307510376 с.
Результат numpy: 21081849486.442448.
0.04503917694091797 с.
